### ISSUE TITLE
ModuleNotFoundError in Mask R-CNN for Bin Picking

### ISSUE THREAD

**Issue by adityaanirudhk** [RussTedrake/manipulation#237]
Hi. Im trying to run the code provided in example 9.2 on Google Colab and I'm receiving a ModuleNotFoundError. I have tried to find the root cause for this problem but couldn't find any. It would be helpful if you could suggest another way to run the code.
![Error](https://github.com/RussTedrake/manipulation/assets/103492081/4e7f0bb5-52f2-4310-8326-1c7680f12c9e)

**Comment by cohnt** [comment]
Make sure you `pip install manipulation`, otherwise the package won't be available. To run everything in this notebook on colab, I needed `!pip install drake manipulation pyvirtualdisplay xvfbwrapper` and `!apt install xvfb` at the top. You also may find that Deepnote supports the textbook examples a bit more easily than Colab.

**Comment by adityaanirudhk** [comment]
Thank you. I'll make sure I check that out.

**Comment by RussTedrake** [comment]
Thanks @cohnt !
